### ISSUE TITLE
User type

### ISSUE THREAD

**Issue by cuginoAle** [Telegram-Mini-Apps/tma.js#111]
**Platform**

Select one of the following:

[//]: # (To make as selected, use [x] instead of [ ].)

- [ ] Telegram for Android
- [ ] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [x] Telegram Web A
- [ ] Telegram Web K

**Describe the bug**
The user type definition doesn't match the latest Telegram implementation.
I.e.: the login event returns an interface for the `User` like the following:
```ts
  first_name: string;
  last_name?: string;
...
```

while this library exposes the following interface:
```ts 
  firstName: string;
  lastName?: string;
...
```

<img width="979" alt="image" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/1298616/79f12b1f-1829-42d7-ba59-44800d54b23f">

Am I doing something wrong?

thanks for the great work!

**To Reproduce**

**Expected behavior**

**Comment by heyqbnk** [comment]
Hey! I don't really get what "login" event is. According to file name where `User` type is defined (`types.d.ts`) on your screenshot, you are probably using the package not related to this repo. 

Where is it from?

**Comment by cuginoAle** [comment]
> Hey! I don't really get what "login" event is. According to file name where `User` type is defined (`types.d.ts`) on your screenshot, you are probably using the package not related to this repo.
> 
> Where is it from? And could you provide this little piece of code including that, where this `user` variable is defined?

Hi, 
in that example I am using the [Telegram Login Widget](https://core.telegram.org/widgets/login), so in that case `user` comes from the login callback, but I have the same problem when processing messages coming from the Bot.

It looks like the data I receive is in `snake_case` while the TS type follows the `camelCase`

**Comment by heyqbnk** [comment]
I am not sure, I can help with this. It seems like this declarations file (`types.d.ts`) is taken by TypeScript from somewhere, not from this package. I can suggest you 2 options:

1. Show minimal reproducible example to get the error you have, so I could find out what is wrong.
2. Ask for help other external developers in Telegram chat: https://t.me/twa_dev

I am also not sure about Telegram Login Widget. You don't really need it because if user is opening Mini App, he is already logged in and you could get his data from the current environment.

**Comment by cuginoAle** [comment]
Hi, thanks for taking the time to look into this.
So, the `type.d.ts` file comes from here:
<img width="495" alt="image" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/1298616/a31995e9-9c46-47bd-a158-498422f0cd5c">


is that correct?

**Comment by heyqbnk** [comment]
Ah, I forgot that I updated declarations files names in one of the latest updates. Yeah, for some reason TypeScript references typings from @tma.js

Could you show the following files?

1. tsconfig.json
2. Code, where this 'user' is defined

**Comment by cuginoAle** [comment]
Sure thing:

<img width="451" alt="image" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/1298616/17fb8e3d-5153-4e22-bac0-63c23a376688">


and this is an example of the `User` usage:

```tsx
  import { useSDK } from '@tma.js/sdk-react';
  ...
    const sdk = useSDK();
    const user = sdk.components?.initData?.user;

```

**Comment by heyqbnk** [comment]
Yeah, `user` from `sdk.components.initData` has no snake case properties. The problem is you copied an example of code from somewhere and I assume, it is code usage example for Telegram Login Widget. The reason is you are using `user` from the SDK, not from event from Telegram Login Widget

**Comment by cuginoAle** [comment]
Hi,
sorry there's something I am not  getting... The  official Telegram doc itself uses `snake_case`:

<img width="373" alt="image" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/1298616/bc9e6d6f-210c-43cb-953e-45ce51c52045">

I import the  user type from `import { User } from '@tma.js/init-data';`

Where should I  get  the type from?

**Comment by heyqbnk** [comment]
`User` described in the doc you referred to has nothing in common with `User` type in `@tma.js/init-data`. Originally `@tma.js/init-data` describes type [WebAppInitData](https://core.telegram.org/bots/webapps#webappinitdata), which has field `user` of type [WebAppUser](https://core.telegram.org/bots/webapps#webappuser).

The reason why package `User` type uses camel casing, but not snake casing is usually JS developers are working with camel case variables and properties names. To receive such type you should utilize parsing method from `@tma.js/init-data`, it will automatically convert object properties to camel case.

Nevertheless, your problem is misunderstanding the entities you are working with. User in Telegram Login Widget is not the same entity as User in `@tma.js/init-data`. So you don't really need `@tma.js/init-data` here.

To solve your problem, you should define User type by yourself. Here is the possible code:
```typescript
interface LoginWidgetUser {
  id: number;
  first_name: string;
  last_name: string;
  username?: string;
}

function onTelegramAuth(user: LoginWidgetUser) {
    console.log(user);
}
```

**Comment by heyqbnk** [comment]
I am sorry, I don't know. I know Telegram team from the side where they don't event use TypeScript, but pure low level JavaScript. You could try asking in Telegram devs chat: https://t.me/twa_dev
