### ISSUE TITLE
Not all CSS variables colors are exposed

### ISSUE THREAD

**Issue by thecoorum** [Telegram-Mini-Apps/tma.js#167]
**Platform**

Select one of the following:

[//]: # (To make as selected, use [x] instead of [ ].)

- [ ] Telegram for Android
- [x] Telegram for iOS
- [x] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

**Describe the bug**

**To Reproduce**

1. Inspect the WebApp with DevTools using the script from the documentation
2. Inspect the WebApp with DevTools using the package
3. Compare and see the amount of colors in the second case is less then in the first one

**Expected behavior**

The amount of colors is the same in both cases

**Comment by heyqbnk** [comment]
Hey! What "colors" are mentioned in this issue?

**Comment by thecoorum** [comment]
Hey @heyqbnk! I was talking about colors that are passed as CSS variables, can't provide the exact list at the moment as using my phone. Can attach it later today

**Comment by heyqbnk** [comment]
Ok, I assume, you are talking about new theme parameters which should appear in `6.10`. Yeah, current packages don't have these new palette keys. Will be updated soon

**Comment by thecoorum** [comment]
6.10? Hmm, can't find the announcement or any mentions of this one. Do you have some references? Also, these keys are already exposed to the `html` if you are embedding script from the docs

**Comment by heyqbnk** [comment]
> Inspect the WebApp with DevTools using the script from the documentation

Could you provide the script you are referring to?

**Comment by thecoorum** [comment]
The one from https://core.telegram.org/bots/webapps#initializing-mini-apps

`<script src="https://telegram.org/js/telegram-web-app.js"></script>`

**Comment by heyqbnk** [comment]
Well, it is not guaranteed, that there will be the same amount of provided CSS variables as in the Telegram SDK. Currently, Telegram SDK parses theme parameters dynamically. So, in case Telegram added new one, it will automatically appear in CSS variables.

Currently, packages extract theme parameters statically and use only known list of palette keys. I should probably rework this bit of logic and switch to dynamic one.

In my mind, you see a higher count of CSS variables there due to new theme keys Telegram is going to introduce in `6.10`.

I created the separate issue for your problem: https://github.com/Telegram-Mini-Apps/tma.js/issues/168
