### ISSUE TITLE
[Bug]: Unhandled Runtime Error: TypeError: undefined is not an object (evaluating 'window.TelegramGameProxy.receiveEvent')

### ISSUE THREAD

**Issue by s-a-y** [Telegram-Mini-Apps/tma.js#342]
### Telegram Application

Telegram for iOS

### Describe the Bug

Mini app shows this error

```
Unhandled Runtime Error
TypeError: undefined is not an object (evaluating 'window.TelegramGameProxy.receiveEvent')
```

### To Reproduce

Just copied nextjs-template repo
pnpm i
pnpm dev
And launched mini app using Telegram on iOS

### Expected Behavior

No error is thrown

**Comment by heyqbnk** [comment]
The nature of this error is the Telegram application not checking whether the `window.TelegramGameProxy` object exists or not. When it wants to emit the event, it just injects a JS code, using this field.

To solve this problem, you can just use raw JS code in the <head/>.

```ts
window.TelegramGameProxy = { receiveEvent() {} };
```

Don't really know if the SDK can do something with that as long as it takes some time for JS to be loaded. During this time the Telegram application may try to emit event.

You can try not adding the code in the head, but do something like that in your root component and check if it works:

```ts
import { subscribe } from '@tma.js/sdk-react';

useEffect(() => {
 return subscribe(() => {});
}, []);
```

The trick here is the `subscribe` method creating the object you need.

**Comment by s-a-y** [comment]
Thanks for the explanation, I'll try

**Comment by nsake** [comment]
Any updates? Does it work?

**Comment by s-a-y** [comment]
Solution above didn't help me or I did it wrong, so moved on to implement everything I need without the lib

**Comment by mlkvs** [comment]
Subject: Issue with Telegram Web App SDK initialization on iOS + Solution

Hello,

I encountered the same problem, which occurs exclusively on iOS. Everything works correctly on Android and desktop PC.

Because of this issue, I couldn't use the Telegram Web App SDK, as it failed to initialize properly.

I was adding the script to the <head> via code for loading.

The solution was to perform manual initialization somewhere in the application.

Here's the code I used for loading and initializing:

```ts
private async loadWebApp(): Promise<void> {
    // Crucial: Pre-define the proxy function *before* loading the script
    (window as any).TelegramGameProxy = {
        receiveEvent: () => {
            console.log("[TelegramGameProxy] [Mock] receiveEvent");
        }
    };

    const url = "https://telegram.org/js/telegram-web-app.js";

    // Check if the script is already loaded to avoid duplicates
    for (let index = 0, count = document.scripts.length; index < count; ++index) {
        const script = document.scripts[index];
        if (script.src.startsWith(url)) {
            return;
        }
    }

    // Load the script with specific attributes
    try {
        await Script.loadAsync(url, "", "anonymous", "no-referrer");
    } catch (error) {
        console.error(error);
    }
}
```

The Key Insight: The problem is how the script is loaded.
Simply appending the script to the <head> triggers iOS's security policy in the WebView, which blocks the context and prevents initialization.

To solve this, I created a utility class for runtime script loading with specific attributes:

```ts
export class Script {
    public static load(
        url: string,
        integrity?: string,
        crossorigin?: string,
        referrerPolicy?: string,
        on_loaded?: () => void,
        on_error: OnErrorEventHandler = null
    ): void {
        const script = document.createElement("script");
        script.src = url;

        if (integrity) script.integrity = integrity;
        if (crossorigin) script.crossOrigin = crossorigin;
        if (referrerPolicy) script.referrerPolicy = referrerPolicy;

        script.onload = on_loaded;
        script.onerror = on_error;

        document.head.appendChild(script);
    }

    public static loadAsync(
        url: string,
        integrity?: string,
        crossorigin?: string,
        referrerPolicy?: string
    ): Promise<void> {
        return new Promise((resolve, reject) =>
            Script.load(url, integrity, crossorigin, referrerPolicy, resolve, reject)
        );
    }
}
```

Loading the Telegram Web App SDK with the following parameters was crucial:

```ts
await Script.loadAsync(url, "", "anonymous", "no-referrer");
// crossorigin => "anonymous"
// referrerPolicy => "no-referrer"
```

Additional precautions I took:

Pre-defining TelegramGameProxy: This ensures the function exists before the SDK script tries to call it.

1. Duplicate check: Prevents loading the SDK script multiple times.
2. This approach resolved all initialization issues, and it now works flawlessly on iOS.

Hope this helps others facing the same problem!
